# Generated by Django 2.2 on 2019-04-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptdata',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('user', 'time'), name='unique_receipt'),
        ),
        migrations.DeleteModel(
            name='ReceiptData',
        ),
    ]
