# Generated by Django 2.2 on 2019-04-13 11:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('user', 'shop', 'summ', 'time')},
        ),
        migrations.DeleteModel(
            name='ReceiptData',
        ),
    ]
